Repository ErikPlachta/Purrfect-Friend, pull requests merged in 2021-12, with the labels that each got.

#28 Development - Framing in Basics
  about.html
  assets/css/style.css
  assets/images/connie.jpeg
  assets/images/erik.png
  package-lock.json
Labels: enhancement

#39 Feature/imagedisplay
  assets/js/script.js
Labels: enhancement

#45 Add Animations
  assets/css/style.css
  assets/html/navigation.html
  assets/js/script.js
  index.html
  saved.html
Labels: enhancement

#42 Add Cat Cards with Quotes Concept
  assets/css/animations.css
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: enhancement, requirement

#47 Navigation: Updating with new NAV
  about.html
  assets/css/style.css
  assets/html/navigation.html
  assets/js/script.js
  index.html
Labels: enhancement

#48 Finalized Development - Built App Like UI overlay experience.
  assets/css/animations.css
  assets/css/style.css
  assets/html/navigation.html
  assets/js/script.js
  index.html
Labels: enhancement, requirement

#53 Update README.md
  README.md
Labels: documentation

#56 Add modal with Bulma framework
  .vscode/settings.json
  assets/css/style.css
  assets/html/navigation.html
  index.html
  test.html
Labels: enhancement, requirement

#57 Add styling to modal. Add styling to quotes. Add gif and polished readme
  README.md
  about.html
  assets/css/style.css
  assets/images/demo.gif
  index.html
  test.html
Labels: documentation, enhancement, requirement
